(function(rules){
    rules.classes = {
        barbarian:{
            combat:{
                bab:'melee'
            }
        },
        bard:{
            combat:{
                bab:'hybrid'
            }
        },
        cleric:{
            combat:{
                bab:'hybrid'
            }
        },
        druid:{
            combat:{
                bab:'hybrid'
            }
        },
        fighter:{
            combat:{
                bab:'melee'
            }
        },
        monk:{
            combat:{
                bab:'hybrid'
            }
        },
        paladin:{
            combat:{
                bab:'melee'
            }
        },
        ranger:{
            combat:{
                bab:'melee'
            }
        },
        rogue:{
            combat:{
                bab:'hybrid'
            }
        },
        sorcerer:{
            combat:{
                bab:'caster'                
            }
        },
        wizard:{
            combat:{
                bab:'caster'                
            }
        }
    };
}(rules));